### PR TITLE
Pin pytest in test_sdists.sh.

### LINKED ISSUE #6763: test_sdists.sh is broken
I just ran https://github.com/certbot/certbot/blob/master/tests/letstest/scripts/test_sdists.sh and it failed with output like:
```
...
+ python setup.py build
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/acme
copying acme/jose_test.py -> build/lib.linux-x86_64-2.7/acme
copying acme/client_test.py -> build/lib.linux-x86_64-2.7/acme
copying acme/magic_typing.py -> build/lib.linux-x86_64-2.7/acme
copying acme/errors_test.py -> build/lib.linux-x86_64-2.7/acme
copying acme/crypto_util_test.py -> build/lib.linux-x86_64-2.7/acme
copying acme/__init__.py -> build/lib.linux-x86_64-2.7/acme
copying acme/fields.py -> build/lib.linux-x86_64-2.7/acme
copying acme/standalone.py -> build/lib.linux-x86_64-2.7/acme
copying acme/crypto_util.py -> build/lib.linux-x86_64-2.7/acme
copying acme/challenges.py -> build/lib.linux-x86_64-2.7/acme
copying acme/messages_test.py -> build/lib.linux-x86_64-2.7/acme
copying acme/test_util.py -> build/lib.linux-x86_64-2.7/acme
copying acme/messages.py -> build/lib.linux-x86_64-2.7/acme
copying acme/challenges_test.py -> build/lib.linux-x86_64-2.7/acme
copying acme/jws_test.py -> build/lib.linux-x86_64-2.7/acme
copying acme/client.py -> build/lib.linux-x86_64-2.7/acme
copying acme/fields_test.py -> build/lib.linux-x86_64-2.7/acme
copying acme/standalone_test.py -> build/lib.linux-x86_64-2.7/acme
copying acme/util.py -> build/lib.linux-x86_64-2.7/acme
copying acme/magic_typing_test.py -> build/lib.linux-x86_64-2.7/acme
copying acme/jws.py -> build/lib.linux-x86_64-2.7/acme
copying acme/util_test.py -> build/lib.linux-x86_64-2.7/acme
copying acme/errors.py -> build/lib.linux-x86_64-2.7/acme
running egg_info
writing requirements to acme.egg-info/requires.txt
writing acme.egg-info/PKG-INFO
writing top-level names to acme.egg-info/top_level.txt
writing dependency_links to acme.egg-info/dependency_links.txt
reading manifest file 'acme.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'acme.egg-info/SOURCES.txt'
creating build/lib.linux-x86_64-2.7/acme/testdata
copying acme/testdata/README -> build/lib.linux-x86_64-2.7/acme/testdata
copying acme/testdata/cert-100sans.pem -> build/lib.linux-x86_64-2.7/acme/testdata
copying acme/testdata/cert-idnsans.pem -> build/lib.linux-x86_64-2.7/acme/testdata
copying acme/testdata/cert-nocn.der -> build/lib.linux-x86_64-2.7/acme/testdata
copying acme/testdata/cert-san.pem -> build/lib.linux-x86_64-2.7/acme/testdata
copying acme/testdata/cert.der -> build/lib.linux-x86_64-2.7/acme/testdata
copying acme/testdata/cert.pem -> build/lib.linux-x86_64-2.7/acme/testdata
copying acme/testdata/critical-san.pem -> build/lib.linux-x86_64-2.7/acme/testdata
copying acme/testdata/csr-100sans.pem -> build/lib.linux-x86_64-2.7/acme/testdata
copying acme/testdata/csr-6sans.pem -> build/lib.linux-x86_64-2.7/acme/testdata
copying acme/testdata/csr-idnsans.pem -> build/lib.linux-x86_64-2.7/acme/testdata
copying acme/testdata/csr-nosans.pem -> build/lib.linux-x86_64-2.7/acme/testdata
copying acme/testdata/csr-san.pem -> build/lib.linux-x86_64-2.7/acme/testdata
copying acme/testdata/csr.der -> build/lib.linux-x86_64-2.7/acme/testdata
copying acme/testdata/csr.pem -> build/lib.linux-x86_64-2.7/acme/testdata
copying acme/testdata/dsa512_key.pem -> build/lib.linux-x86_64-2.7/acme/testdata
copying acme/testdata/rsa1024_key.pem -> build/lib.linux-x86_64-2.7/acme/testdata
copying acme/testdata/rsa2048_cert.pem -> build/lib.linux-x86_64-2.7/acme/testdata
copying acme/testdata/rsa2048_key.pem -> build/lib.linux-x86_64-2.7/acme/testdata
copying acme/testdata/rsa256_key.pem -> build/lib.linux-x86_64-2.7/acme/testdata
copying acme/testdata/rsa512_key.pem -> build/lib.linux-x86_64-2.7/acme/testdata
+ python setup.py test
running test
Searching for pytest
Reading https://pypi.org/simple/pytest/
Downloading https://files.pythonhosted.org/packages/0d/c4/8093b4ffdde66628d4cb138d1d53726e2c21c23ac397cb75494e3f4310c9/pytest-4.2.0-py2.py3-none-any.whl#sha256=6ac6d467d9f053e95aaacd79f831dbecfe730f419c6c7022cb316b365cd9199d
Best match: pytest 4.2.0
Processing pytest-4.2.0-py2.py3-none-any.whl
Installing pytest-4.2.0-py2.py3-none-any.whl to /tmp/tmp.fsgYfO4A89/acme-0.32.0.dev0/.eggs
writing requirements to /tmp/tmp.fsgYfO4A89/acme-0.32.0.dev0/.eggs/pytest-4.2.0-py2.7.egg/EGG-INFO/requires.txt

Installed /tmp/tmp.fsgYfO4A89/acme-0.32.0.dev0/.eggs/pytest-4.2.0-py2.7.egg
Searching for py>=1.5.0
Reading https://pypi.org/simple/py/
Downloading https://files.pythonhosted.org/packages/3e/c7/3da685ef117d42ac8d71af525208759742dd235f8094221fdaafcd3dba8f/py-1.7.0-py2.py3-none-any.whl#sha256=e76826342cefe3c3d5f7e8ee4316b80d1dd8a300781612ddbc765c17ba25a6c6
Best match: py 1.7.0
Processing py-1.7.0-py2.py3-none-any.whl
Installing py-1.7.0-py2.py3-none-any.whl to /tmp/tmp.fsgYfO4A89/acme-0.32.0.dev0/.eggs

Installed /tmp/tmp.fsgYfO4A89/acme-0.32.0.dev0/.eggs/py-1.7.0-py2.7.egg
Searching for pluggy>=0.7
Reading https://pypi.org/simple/pluggy/
Downloading https://files.pythonhosted.org/packages/2d/60/f58d9e8197f911f9405bf7e02227b43a2acc2c2f1a8cbb1be5ecf6bfd0b8/pluggy-0.8.1-py2.py3-none-any.whl#sha256=980710797ff6a041e9a73a5787804f848996ecaa6f8a1b1e08224a5894f2074a
Best match: pluggy 0.8.1
Processing pluggy-0.8.1-py2.py3-none-any.whl
Installing pluggy-0.8.1-py2.py3-none-any.whl to /tmp/tmp.fsgYfO4A89/acme-0.32.0.dev0/.eggs
writing requirements to /tmp/tmp.fsgYfO4A89/acme-0.32.0.dev0/.eggs/pluggy-0.8.1-py2.7.egg/EGG-INFO/requires.txt

Installed /tmp/tmp.fsgYfO4A89/acme-0.32.0.dev0/.eggs/pluggy-0.8.1-py2.7.egg
Searching for pathlib2>=2.2.0
Reading https://pypi.org/simple/pathlib2/
Downloading https://files.pythonhosted.org/packages/2a/46/c696dcf1c7aad917b39b875acdc5451975e3a9b4890dca8329983201c97a/pathlib2-2.3.3-py2.py3-none-any.whl#sha256=5887121d7f7df3603bca2f710e7219f3eca0eb69e0b7cc6e0a022e155ac931a7
Best match: pathlib2 2.3.3
Processing pathlib2-2.3.3-py2.py3-none-any.whl
Installing pathlib2-2.3.3-py2.py3-none-any.whl to /tmp/tmp.fsgYfO4A89/acme-0.32.0.dev0/.eggs
writing requirements to /tmp/tmp.fsgYfO4A89/acme-0.32.0.dev0/.eggs/pathlib2-2.3.3-py2.7.egg/EGG-INFO/requires.txt

Installed /tmp/tmp.fsgYfO4A89/acme-0.32.0.dev0/.eggs/pathlib2-2.3.3-py2.7.egg
Searching for more-itertools>=4.0.0
Reading https://pypi.org/simple/more-itertools/
Downloading https://files.pythonhosted.org/packages/dd/f4/cdfbb6f07f767e0cd8a11b16adfecc735b6eb87dbebda026ce8898e1cc22/more-itertools-6.0.0.tar.gz#sha256=590044e3942351a1bdb1de960b739ff4ce277960f2425ad4509446dbace8d9d1
Best match: more-itertools 6.0.0
Processing more-itertools-6.0.0.tar.gz
Writing /tmp/easy_install-zsprze/more-itertools-6.0.0/setup.cfg
Running more-itertools-6.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-zsprze/more-itertools-6.0.0/egg-dist-tmp-jj95St
warning: no files found matching 'fabfile.py'
  File "build/bdist.linux-x86_64/egg/more_itertools/tests/test_more.py", line 892
    print(item, file=f)
                    ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/more_itertools/more.py", line 329
    def _collate(*iterables, key=lambda a: a, reverse=False):
                               ^
SyntaxError: invalid syntax

zip_safe flag not set; analyzing archive contents...
Moving more_itertools-6.0.0-py2.7.egg to /tmp/tmp.fsgYfO4A89/acme-0.32.0.dev0/.eggs

Installed /tmp/tmp.fsgYfO4A89/acme-0.32.0.dev0/.eggs/more_itertools-6.0.0-py2.7.egg
Searching for attrs>=17.4.0
Reading https://pypi.org/simple/attrs/
Downloading https://files.pythonhosted.org/packages/3a/e1/5f9023cc983f1a628a8c2fd051ad19e76ff7b142a0faf329336f9a62a514/attrs-18.2.0-py2.py3-none-any.whl#sha256=ca4be454458f9dec299268d472aaa5a11f67a4ff70093396e1ceae9c76cf4bbb
Best match: attrs 18.2.0
Processing attrs-18.2.0-py2.py3-none-any.whl
Installing attrs-18.2.0-py2.py3-none-any.whl to /tmp/tmp.fsgYfO4A89/acme-0.32.0.dev0/.eggs
writing requirements to /tmp/tmp.fsgYfO4A89/acme-0.32.0.dev0/.eggs/attrs-18.2.0-py2.7.egg/EGG-INFO/requires.txt

Installed /tmp/tmp.fsgYfO4A89/acme-0.32.0.dev0/.eggs/attrs-18.2.0-py2.7.egg
Searching for atomicwrites>=1.0
Reading https://pypi.org/simple/atomicwrites/
Downloading https://files.pythonhosted.org/packages/52/90/6155aa926f43f2b2a22b01be7241be3bfd1ceaf7d0b3267213e8127d41f4/atomicwrites-1.3.0-py2.py3-none-any.whl#sha256=03472c30eb2c5d1ba9227e4c2ca66ab8287fbfbbda3888aa93dc2e28fc6811b4
Best match: atomicwrites 1.3.0
Processing atomicwrites-1.3.0-py2.py3-none-any.whl
Installing atomicwrites-1.3.0-py2.py3-none-any.whl to /tmp/tmp.fsgYfO4A89/acme-0.32.0.dev0/.eggs

Installed /tmp/tmp.fsgYfO4A89/acme-0.32.0.dev0/.eggs/atomicwrites-1.3.0-py2.7.egg
Searching for scandir
Reading https://pypi.org/simple/scandir/
Downloading https://files.pythonhosted.org/packages/16/2a/557af1181e6b4e30254d5a6163b18f5053791ca66e251e77ab08887e8fe3/scandir-1.9.0.tar.gz#sha256=44975e209c4827fc18a3486f257154d34ec6eaec0f90fef0cca1caa482db7064
Best match: scandir 1.9.0
Processing scandir-1.9.0.tar.gz
Writing /tmp/easy_install-wpmhEc/scandir-1.9.0/setup.cfg
Running scandir-1.9.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-wpmhEc/scandir-1.9.0/egg-dist-tmp-OdUTFU
/usr/lib/python2.7/distutils/extension.py:133: UserWarning: Unknown Extension options: 'optional'
  warnings.warn(msg)
zip_safe flag not set; analyzing archive contents...
Moving scandir-1.9.0-py2.7-linux-x86_64.egg to /tmp/tmp.fsgYfO4A89/acme-0.32.0.dev0/.eggs

Installed /tmp/tmp.fsgYfO4A89/acme-0.32.0.dev0/.eggs/scandir-1.9.0-py2.7-linux-x86_64.egg
running egg_info
writing requirements to acme.egg-info/requires.txt
writing acme.egg-info/PKG-INFO
writing top-level names to acme.egg-info/top_level.txt
writing dependency_links to acme.egg-info/dependency_links.txt
reading manifest file 'acme.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'acme.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 87, in <module>
    cmdclass={"test": PyTest},
  File "/home/ubuntu/letsencrypt/venv/local/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/ubuntu/letsencrypt/venv/local/lib/python2.7/site-packages/setuptools/command/test.py", line 228, in run
    self.run_tests()
  File "setup.py", line 49, in run_tests
    import pytest
  File "/tmp/tmp.fsgYfO4A89/acme-0.32.0.dev0/.eggs/pytest-4.2.0-py2.7.egg/pytest.py", line 14, in <module>
    from _pytest.fixtures import fillfixtures as _fillfuncargs
  File "/tmp/tmp.fsgYfO4A89/acme-0.32.0.dev0/.eggs/pytest-4.2.0-py2.7.egg/_pytest/fixtures.py", line 16, in <module>
    from more_itertools import flatten
  File "build/bdist.linux-x86_64/egg/more_itertools/__init__.py", line 1, in <module>
  File "/tmp/tmp.fsgYfO4A89/acme-0.32.0.dev0/.eggs/more_itertools-6.0.0-py2.7.egg/more_itertools/more.py", line 329
    def _collate(*iterables, key=lambda a: a, reverse=False):
                               ^
SyntaxError: invalid syntax
```
Apparently there is a bug in the latest version of one of `pytest`'s dependencies. See https://stackoverflow.com/questions/54648246/invalid-syntax-in-more-itertools-when-running-pytest.

I'm working on a simple PR to also pin the version of `pytest` used in these tests.

### PR DESCRIPTION
**Pull request by bmw**
Fixes #6763.

By the time this gets reviewed, the immediate problem may have already been fixed by changes to the packages on PyPI, but making this change should make things more resilient going forward.

I tested this on the test farm and all images (that were supposed to) passed.

### CODE REVIEW

File: tests/letstest/scripts/test_sdists.sh [hunk 1]
```diff
@@ -12,6 +12,8 @@ export VENV_ARGS="-p $PYTHON"
 # setup venv
 tools/_venv_common.py --requirement letsencrypt-auto-source/pieces/dependency-requirements.txt
 . ./venv/bin/activate
+# pytest is needed to run tests on some of our packages so we install a pinned version here.
+tools/pip_install.py pytest
```
Comment (ohemorange) [inline tests/letstest/scripts/test_sdists.sh]: Why not pin pytest for all of our installations? Presumably an older version is getting installed over on line 13?

Comment (bmw) [reply tests/letstest/scripts/test_sdists.sh]: We have `pytest` pinned in [dev_constraints.txt](https://github.com/certbot/certbot/blob/bb1242c04767c8686de39af78f4f562ae33ded1d/tools/dev_constraints.txt#L50) which `tools/pip_install.py` is using. In general, as long as we use our scripts in `tools`, everything is pinned down (unless you set the environment variable `CERTBOT_NO_PIN`). It isn't included in certbot-auto's dependencies being used on line 13 though because it doesn't need to be installed when we're not running tests.

We could potentially do something like install all of `dev_constraints.txt` here if you prefer. This will install a lot of unnecessary stuff and may mask problems if we incorrectly modify `setup.py` in the future (such as a dependency being missing or incorrectly specified in `setup.py` but included properly in our dev tools), but it should pretty robustly install everything we'd ever need.

Comment (ohemorange) [reply tests/letstest/scripts/test_sdists.sh]: How was it getting installed before?

Comment (bmw) [reply tests/letstest/scripts/test_sdists.sh]: `setuptools` pulled it in which you can see in the log I put in #6763.

Comment (ohemorange) [reply tests/letstest/scripts/test_sdists.sh]: 😱

Comment (ohemorange) [reply tests/letstest/scripts/test_sdists.sh]: Ah, I figured it out. I was confused as to why this was only breaking here. Turns out we [pin pytest directly](https://github.com/certbot/certbot/blob/master/tests/letstest/scripts/test_tests.sh) in the only other test farm test to use it. We should probably match how we're doing it in both places?

Comment (bmw) [reply tests/letstest/scripts/test_sdists.sh]: Nice catch! I agree we should take the same approach in both files. I added a commit making that change.

Comment (bmw) [reply tests/letstest/scripts/test_sdists.sh]: I ran test_tests.sh test farm tests with this change and they all passed.

File: tests/letstest/scripts/test_tests.sh [hunk 2]
```diff
@@ -10,9 +11,11 @@ $LE_AUTO --os-packages-only
 LE_AUTO_SUDO="" VENV_PATH="$VENV_NAME" $LE_AUTO --no-bootstrap --version
 . $VENV_NAME/bin/activate
 
+PIP_INSTALL=$("$REPO_ROOT/tools/readlink.py" "$REPO_ROOT/tools/pip_install.py")
```
Comment (ohemorange) [inline tests/letstest/scripts/test_tests.sh]: Approving because sure it'll work but curious -- why do we need the readlink?

Comment (bmw) [reply tests/letstest/scripts/test_tests.sh]: It was to get the absolute path to pip_install.py before we moved to a temporary directory but a much saner thing to do is to just install pytest before changing directories.

I made that change, ran test farm tests again, and they still pass.

**Comment by bmw** [comment]
Thanks for the review!
