### PR TITLE
Handle need to rebootstrap before fetch.py

### LINKED ISSUE #5387: Dropping support for Pythons in fetch.py
If we drop support for a version of Python previously supported by fetch.py, existing certbot-auto installations can fail. If we're unable to reboostrap because we don't have the user's permission, when certbot-auto is run again during phase 1 it will call `DeterminePythonVersion` and if we can't find an appropriate Python, we exit with an error. Instead, we should print a message about being unable to check for upgrades.

### PR DESCRIPTION
**Pull request by bmw**
Fixes #5387.

The
```
# bootstrap, this time installing python3
 certbot/letsencrypt-auto-source/letsencrypt-auto --no-self-upgrade -n > /dev/null 2> /dev/null
```
lines in `centos6_tests.sh` after the test I added may or may not be necessary depending on how #5388 is resolved, but in the worst case `letsencrypt-auto` should effectively be a noop and will just run Certbot.

### CODE REVIEW

File: letsencrypt-auto-source/tests/centos6_tests.sh [hunk 1]
```diff
@@ -47,6 +47,12 @@ if [ $RESULT -eq 0 ]; then
   exit 1
 fi
 
+# Skip self upgrade due to LE_PYTHON value
+if ! LE_PYTHON=nonexistant certbot/letsencrypt-auto-source/letsencrypt-auto 2>&1 | grep -q "WARNING: couldn't find Python"; then
```
Comment (ohemorange) [inline letsencrypt-auto-source/tests/centos6_tests.sh]: nonexistent

Comment (ohemorange) [reply letsencrypt-auto-source/tests/centos6_tests.sh]: unless you're worried nonexistent exists

Comment (bmw) [reply letsencrypt-auto-source/tests/centos6_tests.sh]: The purpose of this was to set `LE_PYTHON` to a nonexistent value, however, the empty string is also a good nonexistent value so I removed setting the variable.

Comment (bmw) [reply letsencrypt-auto-source/tests/centos6_tests.sh]: I read this on my phone last night, didn't notice the spelling difference, and thought you had a problem with this approach, however, I think testing with the real (empty) `LE_PYTHON` value is probably better than testing with a silly value like this so I'm going to leave this PR as is.

Comment (ohemorange) [reply letsencrypt-auto-source/tests/centos6_tests.sh]: Good with either test for now; if something in #5388 I'll fix the test there. Do we not care about line length in leauto?
